# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "309f9793a1f982b7e81eee809c801723"
name = "dermaplane"
handle = "dermaplane-1"
application_url = "https://unsigned-exceptions-casinos-potato.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dermaplanelumohs.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_customers,write_orders,write_products"

[auth]
redirect_urls = [
  "https://unsigned-exceptions-casinos-potato.trycloudflare.com/auth/callback",
  "https://unsigned-exceptions-casinos-potato.trycloudflare.com/auth/shopify/callback",
  "https://unsigned-exceptions-casinos-potato.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
